
[project]
name = "celery_cnc"
version = "0.1.0"
description = "Celery Command & Control"
readme = "README.md"
requires-python = ">=3.13"
license = { file = "LICENSE" }
authors = [{ name = "Christian-Hauke Poensgen" },{ name = "Maximilian Dolling" }]
keywords = ["celery", "monitoring", "observability"]
dependencies = [
  "celery[tblib]",
  "django",
  "fastmcp",
  "pydantic",
  "pydantic-settings",
  "sqlalchemy",
  "uvicorn",
  "prometheus-client",
  "opentelemetry-sdk",
  "opentelemetry-exporter-otlp",
  "pydantic-settings>=2.12.0",
  "pydantic-extra-types>=2.11.0",
]

[dependency-groups]
dev = [
  "celery[librabbitmq,redis]",
  "sqlalchemy",
  "psycopg2-binary",
  "mypy",
  "pytest",
  "pytest-asyncio",
  "pytest-cov",
  "pre-commit",
  "celery-types",
  "django-stubs",
]

[tool.hatch.build.targets.wheel]
packages = ["celery_cnc"]

[tool.hatch.build.targets.wheel.force-include]
"celery_cnc/web/templates" = "celery_cnc/web/templates"
"celery_cnc/web/static" = "celery_cnc/web/static"
"celery_cnc/py.typed" = "celery_cnc/py.typed"

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = ["ALL"]

[tool.ruff.lint.mccabe]
max-complexity = 20

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["D", "PLR2004", "S101"]


[tool.mypy]
python_version = "3.13"
files = ["celery_cnc", "tests", "demo"]
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
no_implicit_reexport = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
log_cli = "True"
log_level = "ERROR"
log_cli_level = "ERROR"
asyncio_mode = "auto"
filterwarnings = []
asyncio_default_fixture_loop_scope = "session"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
